#!/usr/bin/env python3
"""Aggregate rule-based notes into Workspace_Rebuild/07_RULES."""

import json
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path.home() / "Ai"
WORKSPACE = ROOT / "Workspace_Rebuild"
RULES_DIR = WORKSPACE / "07_RULES"
CURSOR_RULES_DEST = RULES_DIR / "CURSOR_RULES.md"
RULES_INDEX_DEST = RULES_DIR / "RULES_INDEX.md"
AGENT_RULES_DEST = RULES_DIR / "AGENT_RULES.md"
FILE_ORIGIN_MAP = WORKSPACE / "00_INDEX" / "FILE_ORIGIN_MAP.json"
STRUCTURE_MAP = WORKSPACE / "00_INDEX" / "STRUCTURE_MAP.md"

SKIP_PARTS = {"node_modules", ".git", ".turbo", ".next", ".cache"}
RULE_EXTENSIONS = {".mdc", ".md", ".txt"}


def should_skip(path: Path) -> bool:
    return any(part in SKIP_PARTS for part in path.parts)


def demote_markdown_headings(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.startswith("#"):
            stripped = line.lstrip("# ")
            lines.append(f"#### {stripped}".rstrip())
        else:
            lines.append(line)
    return "\n".join(lines).strip()


def collect_cursor_rules(root: Path):
    rules = defaultdict(list)
    for path in root.rglob("*.mdc"):
        if should_skip(path):
            continue
        if "rules" not in path.parts:
            continue
        try:
            rel = path.relative_to(root)
        except ValueError:
            continue
        parts = list(rel.parts)
        if ".cursor" not in parts:
            continue
        cursor_idx = parts.index(".cursor")
        project = "/".join(parts[:cursor_idx]) or "root"
        content = path.read_text(encoding="utf-8", errors="replace")
        rules[project].append({
            "rule_type": path.stem,
            "source_path": rel.as_posix(),
            "content": demote_markdown_headings(content),
        })
    return rules


def collect_agent_files(root: Path):
    agent_files = []
    for path in root.rglob("AGENTS.md"):
        if should_skip(path):
            continue
        if path.is_relative_to(WORKSPACE):
            continue
        agent_files.append(path)
    return agent_files


def summarize_agent_file(path: Path, limit: int = 10):
    lines = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("---"):
            continue
        if stripped.startswith(">"):
            stripped = stripped.lstrip("> ")
        lines.append(stripped)
        if len(lines) >= limit:
            break
    return lines


def ensure_rules_dir():
    RULES_DIR.mkdir(parents=True, exist_ok=True)


def write_cursor_rules(rules):
    lines = [
        "# Cursor Rule Catalog",
        "",
        "Aggregated Cursor rule packs discovered under `.cursor/rules` directories.",
        "",
    ]
    provenance = []
    for project in sorted(rules.keys()):
        entries = sorted(rules[project], key=lambda x: x["rule_type"].lower())
        lines.append(f"## Project: {project}")
        lines.append("")
        lines.append(f"- Source directory: `{project}/.cursor/rules/`")
        lines.append("")
        for item in entries:
            lines.append(f"### Rule Pack: {item['rule_type']}")
            lines.append("")
            lines.append(f"_Source file_: `{item['source_path']}`")
            lines.append("")
            demoted = item["content"].splitlines()
            if demoted:
                lines.extend(demoted)
                if demoted[-1].strip():
                    lines.append("")
            lines.append("---")
            lines.append(f"Provenance: `{item['source_path']}`")
            lines.append("")
            provenance.append(item["source_path"])
    lines.append("> Catalog generated by App2/tools/extract_rules.py")
    CURSOR_RULES_DEST.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return provenance


def write_rules_index(rules):
    lines = [
        "# Rules Index",
        "",
        "Project | Rule Packs | Source",
        "---|---|---",
    ]
    provenance = set()
    for project in sorted(rules.keys()):
        pack_names = ", ".join(sorted(item["rule_type"] for item in rules[project]))
        source_dir = f"`{project}/.cursor/rules/`"
        lines.append(f"{project} | {pack_names} | {source_dir}")
        provenance.add(f"{project}/.cursor/rules/")
    lines.append("")
    lines.append("---")
    lines.append("Provenance:")
    for src in sorted(provenance):
        lines.append(f"- {src}")
    RULES_INDEX_DEST.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return provenance


def write_agent_rules(agent_files):
    lines = [
        "# Agent Rule Summary",
        "",
        "Condensed checkpoints from AGENTS.md files across the workspace.",
        "",
    ]
    provenance = []
    for path in sorted(agent_files):
        rel = path.relative_to(ROOT).as_posix()
        lines.append(f"## {rel}")
        lines.append("")
        summary_points = summarize_agent_file(path)
        if summary_points:
            for point in summary_points:
                lines.append(f"- {point}")
        else:
            lines.append("- (No textual summary extracted; see source file.)")
        lines.append("")
        lines.append("---")
        lines.append(f"Provenance: `{rel}`")
        lines.append("")
        provenance.append(rel)
    lines.append("> Full texts remain in Workspace_Rebuild/AGENTS.md and original AGENTS.md files.")
    AGENT_RULES_DEST.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return provenance


def refresh_structure_map(base: Path):
    lines = []
    for path in sorted(base.rglob("*")):
        rel = path.relative_to(base)
        indent = rel.as_posix().count("/")
        name = path.name + ("/" if path.is_dir() else "")
        lines.append("  " * indent + f"- {name}")
    STRUCTURE_MAP.write_text("\n".join(lines) + "\n", encoding="utf-8")


def update_origin_map(cursor_sources, index_sources, agent_sources):
    if not FILE_ORIGIN_MAP.exists():
        data = []
    else:
        data = json.loads(FILE_ORIGIN_MAP.read_text(encoding="utf-8"))
    filtered = [
        entry for entry in data
        if not str(entry.get("dest_path", "")).startswith("Workspace_Rebuild/07_RULES/")
    ]
    for src in cursor_sources:
        filtered.append({
            "source_path": src,
            "dest_path": "Workspace_Rebuild/07_RULES/CURSOR_RULES.md",
            "reason": "cursor_rules_catalog",
            "tags": ["rules", "cursor"],
        })
    for src in index_sources:
        filtered.append({
            "source_path": src,
            "dest_path": "Workspace_Rebuild/07_RULES/RULES_INDEX.md",
            "reason": "cursor_rules_index",
            "tags": ["rules", "index"],
        })
    for src in agent_sources:
        filtered.append({
            "source_path": src,
            "dest_path": "Workspace_Rebuild/07_RULES/AGENT_RULES.md",
            "reason": "agent_rules_summary",
            "tags": ["rules", "agents"],
        })
    FILE_ORIGIN_MAP.write_text(json.dumps(filtered, indent=2), encoding="utf-8")


def main():
    ensure_rules_dir()
    cursor_rules = collect_cursor_rules(ROOT)
    agent_files = collect_agent_files(ROOT)

    cursor_provenance = write_cursor_rules(cursor_rules)
    index_provenance = write_rules_index(cursor_rules)
    agent_provenance = write_agent_rules(agent_files)

    refresh_structure_map(WORKSPACE)
    update_origin_map(cursor_provenance, index_provenance, agent_provenance)

    print("Rule summaries written to", RULES_DIR)


if __name__ == "__main__":
    main()

